name: EXERCISE

channels:
  - conda-forge

dependencies:
  - python=3.14
  - jupyterlab
  - jupyterlab-language-pack-ja-jp
  - ipykernel
  - numpy
  - scipy
  - matplotlib
  - pandas
  - plotly
  - pip
  - pip:
      - pygame-ce
