# jb/_config.yml
title: "流体工学セミナー・教材集"
# author: "KONNO Akihisa"
copyright: "2025 KONNO Akihisa"
language: ja
execute:
  execute_notebooks: "off"
parse:
  myst_enable_extensions:
    - deflist
html:
  meta:
    robots: noindex, nofollow
